import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Anh Nguyen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="">Home</main>
    </>
  );
}
